api-controllers:
    resource: ../../src/Api/Controller/
    type: annotation
    prefix: /sugoma

core-controllers:
    resource: ../../src/Core/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
