security:
  role_hierarchy:
    !php/const App\Core\User\Enum\Role::ADMIN:
      - !php/const App\Core\User\Enum\Role::USER
      - !php/const App\Core\User\Enum\Role::WORKER
      - !php/const App\Core\User\Enum\Role::CHIEF
      - !php/const App\Core\User\Enum\Permission::USER_CREATE
      - !php/const App\Core\User\Enum\Permission::USER_UPDATE
      - !php/const App\Core\User\Enum\Permission::USER_DELETE
      - !php/const App\Core\User\Enum\Permission::USER_VALIDATION
    !php/const App\Core\User\Enum\Role::CHIEF:
      - !php/const App\Core\User\Enum\Role::USER
      - !php/const App\Core\User\Enum\Role::WORKER
      - !php/const App\Core\User\Enum\Permission::CLINIC_CREATE
      - !php/const App\Core\User\Enum\Permission::CLINIC_UPDATE
      - !php/const App\Core\User\Enum\Permission::CLINIC_DELETE
    !php/const App\Core\User\Enum\Role::WORKER:
      - !php/const App\Core\User\Enum\Role::USER
      - !php/const App\Core\User\Enum\Permission::USER_CONTACT_CREATE
      - !php/const App\Core\User\Enum\Permission::USER_SHOW
      - !php/const App\Core\User\Enum\Permission::USER_INDEX
      - !php/const App\Core\User\Enum\Permission::CLINIC_APPOINTMENT_CREATE
      - !php/const App\Core\User\Enum\Permission::CLINIC_APPOINTMENT_UPDATE
      - !php/const App\Core\User\Enum\Permission::CLINIC_APPOINTMENT_DELETE
    !php/const App\Core\User\Enum\Role::USER:
      - !php/const App\Core\User\Enum\Permission::CLINIC_SHOW
      - !php/const App\Core\User\Enum\Permission::CLINIC_INDEX
      - !php/const App\Core\User\Enum\Permission::CLINIC_APPOINTMENT_SHOW
      - !php/const App\Core\User\Enum\Permission::CLINIC_APPOINTMENT_INDEX
