version: "3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --slow_query_log=1 --log_output=TABLE --long-query-time=1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: project2021
    ports:
      - 3306:3306
