version: "3"
services:

  mongodb:
    image: mongo
    container_name: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --slow_query_log=1 --log_output=TABLE --long-query-time=1
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: project2021
    ports:
      - 3306:3306

