api-controllers:
    resource: ../../src/Api/
    type: annotation
    prefix: /api/v1
app-controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /api/v1

kernel:
    resource: ../../src/Kernel.php
    type: annotation
